  apiVersion: v1
  kind: Pod
  metadata:
    name: store-admin-web-pod
    labels:
      app: store-admin-web
  spec:
    containers:
    - name: store-admin-web-container
      image: store-admin-web:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      env:
      - name: NODE_ENV
        value: "production"
